/* Generated By:JJTree: Do not edit this line. .\Simple1TreeConstants.java */

public interface Simple1TreeConstants
{
  public int JJTINPUT = 0;
  public int JJTMATCHEDBRACES = 1;


  public String[] jjtNodeName = {
    "Input",
    "MatchedBraces",
  };
}
