/* Generated By:JavaCC: Do not edit this line. IdListConstants.java */
public interface IdListConstants {

  int EOF = 0;
  int Id = 5;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<Id>",
  };

}
